name: "Build Manual"
on:
  pull_request:
    paths:
    - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build documentation
      uses: Algo-ryth-mix/sphinx-action@master
      with:
        docs-folder: "docs/"

    - name: Upload documentation
      uses: actions/upload-artifact@v2
      with:
        name: Tiled-Manual-HTML
        path: docs/_build/html/
